sudo: false
os: linux
language: php
php: 7.3

before_install:
  - cp .env.example .env

install:
  - composer install
  - php artisan k:g

script:
  - php vendor/bin/phpcs

cache:
  directories:
    - $HOME/.composer/cache/files
    - vendor
